import { Router } from 'express';
import authRoutes from './auth.routes.js';
import webauthnRoutes from './webauthn.routes.js';
import setupRoutes from './setup.routes.js';
import usersRoutes from './users.routes.js';
import settingsRoutes from './settings.routes.js';
import statusRoutes from './status.routes.js';
import kubernetesRoutes from './kubernetes.routes.js';
import argocdRoutes from './argocd.routes.js';
import haproxyRoutes from './haproxy.routes.js';
import gitlabRoutes from './gitlab.routes.js';
import githubRoutes from './github.routes.js';
import giteaRoutes from './gitea.routes.js';
import proxmoxRoutes from './proxmox.routes.js';
import traefikRoutes from './traefik.routes.js';
import certmanagerRoutes from './certmanager.routes.js';
import grafanaRoutes from './grafana.routes.js';
import tracingRoutes from './tracing.routes.js';
import wazuhRoutes from './wazuh.routes.js';
import proxiesRoutes from './proxies.routes.js';
import domainsRoutes from './domains.routes.js';
import dnsRoutes from './dns.routes.js';
import deploymentsRoutes from './deployments.routes.js';
import networkTopologyRoutes from './networkTopology.routes.js';
import hostsRoutes from './hosts.routes.js';
import backupsRoutes from './backups.routes.js';
import systemRoutes from './system.routes.js';
import auditRoutes from './audit.routes.js';
import groupsRoutes from './groups.routes.js';
import inventoryRoutes from './inventory.routes.js';
import identityRoutes from './identity.routes.js';
import consoleRoutes from './console.routes.js';
import securityRoutes from './security.routes.js';
import imageScansRoutes from './imageScans.routes.js';
import dastScansRoutes from './dastScans.routes.js';
import notificationsRoutes from './notifications.routes.js';
import userNotificationsRoutes from './userNotifications.routes.js';
import featureFlagsRoutes from './featureFlags.routes.js';
import dockerHubRoutes from './dockerHub.routes.js';
import registryRoutes from './registry.routes.js';
import codeScansRoutes from './codeScans.routes.js';
import iacScansRoutes from './iacScans.routes.js';
import iacRoutes from './iac.routes.js';
import sbomRoutes from './sbom.routes.js';
import signaturesRoutes from './signatures.routes.js';
import volumesRoutes from './volumes.routes.js';
import networkServicesRoutes from './networkServices.routes.js';
import devtoolsRoutes from './devtools.routes.js';
import vaultRoutes from './vault.routes.js';
import projectsRoutes from './projects.routes.js';
import organizationsRoutes from './organizations.routes.js';
import serviceAccountsRoutes from './serviceAccounts.routes.js';
import apiV1Routes from './apiV1.routes.js';
import catalogRoutes from './catalog.routes.js';
import environmentBlueprintsRoutes from './environmentBlueprints.routes.js';
import policiesRoutes from './policies.routes.js';
import platformRequestsRoutes from './platformRequests.routes.js';
import jobsRoutes from './jobs.routes.js';
import incidentsRoutes from './incidents.routes.js';
import teamsRoutes from './teams.routes.js';
import webhooksRoutes from './webhooks.routes.js';
import reposRoutes from './repos.routes.js';
import reviewsRoutes from './reviews.routes.js';
import pipelinesRoutes from './pipelines.routes.js';
import shortcutsRoutes from './shortcuts.routes.js';
import terminalRoutes from './terminal.routes.js';
import wikiRoutes from './wiki.routes.js';
import pluginsRoutes from './plugins.routes.js';
import repositoryProvisioningRoutes from './repositoryProvisioning.routes.js';
import personalTokensRoutes from './personalTokens.routes.js';
import certificatesRoutes from './certificates.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/auth/webauthn', webauthnRoutes);
router.use('/setup', setupRoutes);
router.use('/users', usersRoutes);
router.use('/settings', settingsRoutes);
router.use('/status', statusRoutes);
router.use('/kubernetes', kubernetesRoutes);
router.use('/argocd', argocdRoutes);
router.use('/haproxy', haproxyRoutes);
router.use('/gitlab', gitlabRoutes);
router.use('/github', githubRoutes);
router.use('/gitea', giteaRoutes);
router.use('/proxmox', proxmoxRoutes);
router.use('/traefik', traefikRoutes);
router.use('/certmanager', certmanagerRoutes);
router.use('/grafana', grafanaRoutes);
router.use('/tracing', tracingRoutes);
router.use('/wazuh', wazuhRoutes);
router.use('/proxies', proxiesRoutes);
router.use('/domains', domainsRoutes);
router.use('/dns', dnsRoutes);
router.use('/deployments', deploymentsRoutes);
router.use('/network', networkTopologyRoutes);
router.use('/hosts', hostsRoutes);
router.use('/backups', backupsRoutes);
router.use('/system', systemRoutes);
router.use('/audit', auditRoutes);
router.use('/groups', groupsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/identity', identityRoutes);
router.use('/console', consoleRoutes);
router.use('/security', securityRoutes);
router.use('/image-scans', imageScansRoutes);
router.use('/dast-scans', dastScansRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/my-notifications', userNotificationsRoutes);
router.use('/feature-flags', featureFlagsRoutes);
router.use('/docker-hub', dockerHubRoutes);
router.use('/registry', registryRoutes);
router.use('/code-scans', codeScansRoutes);
router.use('/iac-scans', iacScansRoutes);
router.use('/iac', iacRoutes);
router.use('/sbom', sbomRoutes);
router.use('/signatures', signaturesRoutes);
router.use('/volumes', volumesRoutes);
router.use('/network-services', networkServicesRoutes);
router.use('/devtools', devtoolsRoutes);
router.use('/vault', vaultRoutes);
router.use('/projects', projectsRoutes);
router.use('/organizations', organizationsRoutes);
router.use('/organizations/:id/service-accounts', serviceAccountsRoutes);
router.use('/v1', apiV1Routes);
router.use('/catalog', catalogRoutes);
router.use('/environment-blueprints', environmentBlueprintsRoutes);
router.use('/policies', policiesRoutes);
router.use('/platform-requests', platformRequestsRoutes);
router.use('/jobs', jobsRoutes);
router.use('/incidents', incidentsRoutes);
router.use('/teams', teamsRoutes);
router.use('/webhooks', webhooksRoutes);
router.use('/repos', reposRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/pipelines', pipelinesRoutes);
router.use('/shortcuts', shortcutsRoutes);
router.use('/terminal', terminalRoutes);
router.use('/wiki', wikiRoutes);
router.use('/plugins', pluginsRoutes);
router.use('/repository-provisioning', repositoryProvisioningRoutes);
// Monté hors de /users (dont usersRoutes exige déjà requirePermission('users','admin')
// sur tout le préfixe, y compris les sous-chemins non définis) pour rester
// accessible à tout utilisateur authentifié gérant SON propre token.
router.use('/personal-tokens', personalTokensRoutes);
router.use('/certificates', certificatesRoutes);

export default router;
