// Entrées statiques de la recherche globale (Cmd+K). Chaque entrée pointe vers
// une route déjà déclarée dans App.jsx. `adminOnly` masque l'entrée aux comptes
// non-admin, comme le fait déjà DomainNav pour la navigation latérale.
export const STATIC_SEARCH_ITEMS = [
  { label: 'Vue générale', group: 'Pages', path: '/', keywords: 'accueil dashboard tableau de bord santé' },
  { label: 'Développement — Accès aux outils', group: 'Pages', path: '/deployments', keywords: 'dev outils raccourcis chaîne' },
  { label: 'Développement — Projets', group: 'Pages', path: '/deployments/projects', keywords: 'projets équipe backlog tâches' },
  { label: 'Développement — Dépôts Git', group: 'Pages', path: '/deployments/repos', keywords: 'gitlab github dépôt repo forge étiquette rôle' },
  { label: 'Développement — Revue de code', group: 'Pages', path: '/deployments/reviews', keywords: 'merge request pull request relecture revue mr pr' },
  { label: 'Développement — Pipelines CI/CD', group: 'Pages', path: '/deployments/pipelines', keywords: 'ci cd pipeline exécution build' },
  { label: 'Développement — Environnements', group: 'Pages', path: '/deployments/environments', keywords: 'dev staging production intégration versions promotion' },
  { label: 'Développement — Déploiements', group: 'Pages', path: '/deployments/releases', keywords: 'argocd kubernetes application déploiement' },
  { label: 'Développement — Tests & qualité', group: 'Pages', path: '/deployments/tests', keywords: 'tests couverture qualité' },
  { label: 'Développement — Conteneurs', group: 'Pages', path: '/deployments/containers', keywords: 'docker kubernetes pods conteneurs logs' },
  { label: 'Développement — Images & registry', group: 'Pages', path: '/deployments/images', keywords: 'images registry cve signature' },
  { label: 'Développement — Secrets & variables', group: 'Pages', path: '/deployments/secrets', keywords: 'vault secrets mots de passe variables' },
  { label: 'Développement — Supply Chain Security', group: 'Pages', path: '/deployments/supply-chain', keywords: 'sast scan secrets dependances conteneur sbom signature security gate' },
  { label: 'Kubernetes — Terminal sécurisé', group: 'Pages', path: '/kubernetes/terminal', keywords: 'terminal kubectl shell exec rbac' },
  { label: 'Infrastructure — Proxmox', group: 'Pages', path: '/infrastructure', keywords: 'vm lxc nœuds proxmox' },
  { label: 'Infrastructure — Hôtes & agents', group: 'Pages', path: '/infrastructure/hosts', keywords: 'ssh agent wazuh node exporter', adminOnly: true },
  { label: 'Kubernetes', group: 'Pages', path: '/kubernetes', keywords: 'k8s cluster pods namespaces deployments logs' },
  { label: 'Kubernetes — Services', group: 'Pages', path: '/kubernetes/services', keywords: 'k8s clusterip nodeport loadbalancer' },
  { label: 'Réseaux — Topologie', group: 'Pages', path: '/network', keywords: 'schéma réseau graphe' },
  { label: 'Réseaux — Proxies & domaines', group: 'Pages', path: '/network/proxies', keywords: 'reverse proxy domaine traefik haproxy' },
  { label: 'Réseaux — HAProxy', group: 'Pages', path: '/network/haproxy', keywords: 'backend serveur drain maint' },
  { label: 'Réseaux — Certificats', group: 'Pages', path: '/network/certificates', keywords: 'cert-manager tls ssl renouvellement' },
  { label: 'Monitoring', group: 'Pages', path: '/monitoring', keywords: 'grafana alertes métriques' },
  { label: 'Cybersécurité', group: 'Pages', path: '/security', keywords: 'wazuh agents sécurité' },
  { label: 'Stockage', group: 'Pages', path: '/storage', keywords: 'volumes nas sauvegardes' },
  { label: 'Mon compte', group: 'Pages', path: '/account', keywords: 'profil mot de passe avatar thème' },
  { label: "Manuel d'utilisation", group: 'Pages', path: '/manual', keywords: 'aide documentation guide manuel help' },
  { label: 'Rapport de santé', group: 'Pages', path: '/report', keywords: 'rapport pdf export imprimer santé' },
  { label: 'Paramètres — Intégrations', group: 'Administration', path: '/settings', keywords: 'kubernetes argocd haproxy gitlab github proxmox traefik grafana wazuh token', adminOnly: true },
  { label: 'Paramètres — Utilisateurs', group: 'Administration', path: '/settings?tab=users', keywords: 'comptes rôles admin utilisateur', adminOnly: true },
  { label: 'Paramètres — Groupes & permissions', group: 'Administration', path: '/settings?tab=groups', keywords: 'groupes permissions matrice droits rbac', adminOnly: true },
  { label: 'Paramètres — Inventaire', group: 'Administration', path: '/settings?tab=inventory', keywords: 'actifs matériel garantie serveurs', adminOnly: true },
  { label: 'Paramètres — Plateforme', group: 'Administration', path: '/settings?tab=platform', keywords: 'organisation fuseau horaire langue', adminOnly: true },
  { label: 'Paramètres — Connexion & identité', group: 'Administration', path: '/settings?tab=identity', keywords: 'oidc ldap sso session mot de passe', adminOnly: true },
  { label: 'Paramètres — Services Git', group: 'Administration', path: '/settings?tab=git', keywords: 'gitlab github forge miroir', adminOnly: true },
  { label: 'Paramètres — Système', group: 'Administration', path: '/settings?tab=system', keywords: 'version mise à jour sauvegarde backup restaurer', adminOnly: true },
  { label: 'Paramètres — Journal', group: 'Administration', path: '/settings?tab=audit', keywords: 'audit log historique actions', adminOnly: true }
];
